### ISSUE TITLE
Edits to the new GFKB graphs currently in Test 

### ISSUE THREAD

**Issue by steph-sing** [GW-HIVE/GFKB#2]
1) When attempting to toggle between the two graph viewing options (Genus and Species) a few problems arise: 
a) the graph  and data always appears as "Species" rather than being allowed to switch to the "Genus" data. It seems either the Genus data isn't available for to be read, or the script is having trouble loading the Genus option
b) the page reloads each time you try to toggle between the Genus and Species graphs. Is this avoidable?

**Comment by HadleyKing** [comment]
@ProjectProgramAMark
